export const FETCH_POKEMON_START = "FETCH_POKEMON_START";
export const FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS";
export const FETCH_POKEMON_FAILED = "FETCH_POKEMON_FAILED";

export const FETCH_POKEMON_JOHTO_START = "FETCH_POKEMON_JOHTO_START";
export const FETCH_POKEMON_JOHTO_SUCCESS = "FETCH_POKEMON_JOHTO_SUCCESS";
export const FETCH_POKEMON_JOHTO_FAILED = "FETCH_POKEMON_JOHTO_FAILED";

export const FETCH_POKEMON_TYPE_START = "FETCH_POKEMON_TYPE_START";
export const FETCH_POKEMON_TYPE_SUCCESS = "FETCH_POKEMON_TYPE_SUCCESS";
export const FETCH_POKEMON_TYPE_FAILED = "FETCH_POKEMON_TYPE_FAILED";


