export const FETCH_POKEMON_START = "FETCH_POKEMON_START";
export const FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS";
export const FETCH_POKEMON_FAILED = "FETCH_POKEMON_FAILED";
export const FETCH_POKEMON_MORE = "FETC_POKEMON_MORE";
export const FILTER_POKEMON = "FILTER_POKEMON";
export const FILTER_POKEMON_DONE =  "FILTER_POKEMON_DONE";

export const FETCH_POKEMON_JOHTO_START = "FETCH_POKEMON_JOHTO_START";
export const FETCH_POKEMON_JOHTO_SUCCESS = "FETCH_POKEMON_JOHTO_SUCCESS";
export const FETCH_POKEMON_JOHTO_FAILED = "FETCH_POKEMON_JOHTO_FAILED";
export const FILTER_POKEMON_JOHTO = "FILTER_POKEMON_JOHTO";
export const FILTER_POKEMON_JOHTO_DONE =  "FILTER_POKEMON_JOHTO_DONE";



export const FETCH_POKEMON_TYPE_START = "FETCH_POKEMON_TYPE_START";
export const FETCH_POKEMON_TYPE_SUCCESS = "FETCH_POKEMON_TYPE_SUCCESS";
export const FETCH_POKEMON_TYPE_FAILED = "FETCH_POKEMON_TYPE_FAILED";


export const FETCH_POKEMON_HOEN_START = "FETCH_POKEMON_HOEN_START";
export const FETCH_POKEMON_HOEN_SUCCESS = "FETCH_POKEMON_HOEN_SUCCESS";
export const FETCH_POKEMON_HOEN_FAILED = "FETCH_POKEMON_HOEN_FAILED";
export const FILTER_POKEMON_HOEN = "FILTER_POKEMON_HOEN";
export const FILTER_POKEMON_HOEN_DONE =  "FILTER_POKEMON_HOEN_DONE";
export const REMOVE_FILTER = "REMOVE_FILTER";


